version: "3"
services:
  app:
    build: .
    volumes:
      - .:/repository
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL_TYPE=${REACT_APP_API_URL_TYPE}
      - REACT_APP_API_URL_IMAGE=${REACT_APP_API_URL_IMAGE}
      - REACT_APP_API_URL_CLASSIFICATION=${REACT_APP_API_URL_CLASSIFICATION}
    command:
      - yarn start --host 0.0.0.0 --port 3000
    tty: true
