const FETCH_ALL_CLASSIFICATION: string = "FETCH_ALL_CLASSIFICATION";
const DELETE_ONE_CLASSIFICATION_BY_ID: string = "DELETE_ONE_CLASSIFICATION_BY_ID";
const FETCH_ALL_IMAGE: string = "FETCH_ALL_IMAGE";
const UPLOAD_MANY_IMAGE: string = "UPLOAD_MANY_IMAGE";
const CLASSIFY_MANY_IMAGE: string = "CLASSIFY_MANY_IMAGE";
const SELECT_CLASSIFICATION_TYPE: string = "SELECT_CLASSIFICATION_TYPE";
const FETCH_ALL_TYPE: string = "FETCH_ALL_TYPE";

export {
    SELECT_CLASSIFICATION_TYPE,
    FETCH_ALL_TYPE,
    FETCH_ALL_IMAGE,
    UPLOAD_MANY_IMAGE,
    FETCH_ALL_CLASSIFICATION,
    DELETE_ONE_CLASSIFICATION_BY_ID,
    CLASSIFY_MANY_IMAGE
};